using System.Text.Json.Serialization;
using UnityEngine.SceneManagement;

namespace OutwardVoyager;

/// <summary>
/// Reads live game state via IL2CPP interop assemblies generated by BepInEx on first launch.
/// Entry point: SplitScreenManager.Instance.GetLocalPlayer(0).ControlledCharacter
/// </summary>
public class GameStateReader
{
    public GameState ReadCurrentState()
    {
        return new GameState
        {
            SceneName = GetCurrentScene(),
            Player = GetPlayerState(),
            Timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
        };
    }

    private static string GetCurrentScene()
    {
        try
        {
            return SceneManager.GetActiveScene().name ?? "unknown";
        }
        catch
        {
            return "unknown";
        }
    }

    private static PlayerState GetPlayerState()
    {
        try
        {
            var charMgr = CharacterManager.Instance;
            if (charMgr == null) return new PlayerState();

            var character = charMgr.GetFirstLocalCharacter();
            if (character == null) return new PlayerState();

            var pos = character.transform.position;
            var stats = character.Stats;

            float health = 0, maxHealth = 0, stamina = 0, maxStamina = 0, mana = 0, maxMana = 0;

            if (stats != null)
            {
                health = stats.CurrentHealth;
                maxHealth = stats.MaxHealth;
                stamina = stats.CurrentStamina;
                maxStamina = stats.MaxStamina;
                mana = stats.CurrentMana;
                maxMana = stats.MaxMana;
            }

            return new PlayerState
            {
                Health = health,
                MaxHealth = maxHealth,
                Stamina = stamina,
                MaxStamina = maxStamina,
                Mana = mana,
                MaxMana = maxMana,
                PositionX = pos.x,
                PositionY = pos.y,
                PositionZ = pos.z,
                IsDead = character.IsDead,
                IsInCombat = character.InCombat,
            };
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"GameStateReader error: {ex.Message}");
            return new PlayerState();
        }
    }
}

public class GameState
{
    [JsonPropertyName("type")] public string Type { get; init; } = "game_state";
    [JsonPropertyName("scene")] public string SceneName { get; init; } = "";
    [JsonPropertyName("player")] public PlayerState Player { get; init; } = new();
    [JsonPropertyName("timestamp")] public long Timestamp { get; init; }
}

public class PlayerState
{
    [JsonPropertyName("health")] public float Health { get; init; }
    [JsonPropertyName("max_health")] public float MaxHealth { get; init; }
    [JsonPropertyName("stamina")] public float Stamina { get; init; }
    [JsonPropertyName("max_stamina")] public float MaxStamina { get; init; }
    [JsonPropertyName("mana")] public float Mana { get; init; }
    [JsonPropertyName("max_mana")] public float MaxMana { get; init; }
    [JsonPropertyName("pos_x")] public float PositionX { get; init; }
    [JsonPropertyName("pos_y")] public float PositionY { get; init; }
    [JsonPropertyName("pos_z")] public float PositionZ { get; init; }
    [JsonPropertyName("is_dead")] public bool IsDead { get; init; }
    [JsonPropertyName("in_combat")] public bool IsInCombat { get; init; }
}
