using System.Text.Json.Serialization;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace OutwardVoyager;

/// <summary>
/// Reads live game state via IL2CPP interop assemblies generated by BepInEx on first launch.
/// Entry point: SplitScreenManager.Instance.GetLocalPlayer(0).ControlledCharacter
/// </summary>
public class GameStateReader
{
    public GameState ReadCurrentState()
    {
        var playerState = GetPlayerState();
        var playerPos = new Vector3(playerState.PositionX, playerState.PositionY, playerState.PositionZ);

        return new GameState
        {
            SceneName = GetCurrentScene(),
            Player = playerState,
            NearbyDead = GetNearbyDead(playerPos),
            NearbyInteractions = GetNearbyInteractions(playerPos),
            Inventory = GetInventory(),
            ScreenMessage = GetScreenMessage(),
            Timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
        };
    }

    private static string GetCurrentScene()
    {
        try
        {
            return SceneManager.GetActiveScene().name ?? "unknown";
        }
        catch
        {
            return "unknown";
        }
    }

    private static PlayerState GetPlayerState()
    {
        try
        {
            var charMgr = CharacterManager.Instance;
            if (charMgr == null) return new PlayerState();

            var character = charMgr.GetFirstLocalCharacter();
            if (character == null) return new PlayerState();

            var pos = character.transform.position;
            var rot = character.transform.eulerAngles;
            var stats = character.Stats;

            // Camera rotation for camera-relative movement
            float cameraRotY = 0f;
            var cam = Camera.main;
            if (cam != null)
                cameraRotY = cam.transform.eulerAngles.y;

            float health = 0, maxHealth = 0, stamina = 0, maxStamina = 0, mana = 0, maxMana = 0;

            if (stats != null)
            {
                health = stats.CurrentHealth;
                maxHealth = stats.MaxHealth;
                stamina = stats.CurrentStamina;
                maxStamina = stats.MaxStamina;
                mana = stats.CurrentMana;
                maxMana = stats.MaxMana;
            }

            return new PlayerState
            {
                Health = health,
                MaxHealth = maxHealth,
                Stamina = stamina,
                MaxStamina = maxStamina,
                Mana = mana,
                MaxMana = maxMana,
                PositionX = pos.x,
                PositionY = pos.y,
                PositionZ = pos.z,
                RotationY = rot.y,
                CameraRotationY = cameraRotY,
                IsDead = character.IsDead,
                IsInCombat = character.InCombat,
            };
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"GameStateReader error: {ex.Message}");
            return new PlayerState();
        }
    }

    private const float ScanRadius = 100f;

    // Keywords that suggest a visible object is a corpse/body.
    private static readonly string[] CorpseKeywords =
        ["corpse", "dead", "body", "cadaver", "skeleton", "skull", "bones", "remains"];

    private static List<NearbyDeadEntry> GetNearbyDead(Vector3 playerPos)
    {
        var result   = new List<NearbyDeadEntry>();
        var seenIds  = new HashSet<int>();

        var playerChar = CharacterManager.Instance?.GetFirstLocalCharacter();
        int playerInstanceId = playerChar != null ? playerChar.gameObject.GetInstanceID() : -1;

        try
        {
            // ── Pass 1: Collider-based scan (Characters with IsDead, items) ─────
            var colliders = Physics.OverlapSphere(playerPos, ScanRadius);
            foreach (var col in colliders)
            {
                if (col == null) continue;
                var root = col.transform.root.gameObject;
                int id   = root.GetInstanceID();
                if (!seenIds.Add(id)) continue;
                if (id == playerInstanceId) continue;

                var pos  = root.transform.position;
                float dist = FlatDistance(pos, playerPos);

                var ch = root.GetComponentInChildren<Character>();
                if (ch != null)
                {
                    if (!ch.IsDead) continue;
                    result.Add(MakeEntry(ch.UID?.ToString() ?? id.ToString(),
                        ch.name, "character", pos, dist));
                    continue;
                }

                if (MatchesCorpseKeyword(root.name))
                    result.Add(MakeEntry(id.ToString(), root.name, "prop", pos, dist));
            }

            // NOTE: Pass 2 (FindObjectsOfType<Renderer>) was removed — it likely
            // caused game crashes in IL2CPP. Use the "scan_nearby" command instead
            // for thorough on-demand detection via scene hierarchy walk.
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"NearbyDead scan error: {ex.Message}");
        }

        result.Sort((a, b) => a.Distance.CompareTo(b.Distance));

        return result;
    }

    private static bool MatchesCorpseKeyword(string name)
    {
        string lower = name.ToLowerInvariant();
        return Array.Exists(CorpseKeywords, k => lower.Contains(k));
    }

    private static float FlatDistance(Vector3 a, Vector3 b)
    {
        var d = a - b;
        d.y = 0f;
        return d.magnitude;
    }

    private static NearbyDeadEntry MakeEntry(string uid, string name, string source,
        Vector3 pos, float dist) => new()
    {
        Uid = uid, Name = name, Source = source,
        X = pos.x, Y = pos.y, Z = pos.z, Distance = dist,
    };

    // ── Nearby interactions ─────────────────────────────────────────────────

    private const float InteractionRadius = 6f;

    private static List<NearbyInteractionEntry> GetNearbyInteractions(Vector3 playerPos)
    {
        var result = new List<NearbyInteractionEntry>();
        try
        {
            var colliders = Physics.OverlapSphere(playerPos, InteractionRadius);
            var seen = new HashSet<int>();

            foreach (var col in colliders)
            {
                if (col == null) continue;
                var root = col.transform.root.gameObject;
                int id = root.GetInstanceID();
                if (!seen.Add(id)) continue;

                // Look for InteractionActivator on the root or any child
                var activator = root.GetComponentInChildren<InteractionActivator>();
                if (activator == null) continue;
                if (!activator.gameObject.activeInHierarchy) continue;

                var pos = root.transform.position;
                float dist = FlatDistance(pos, playerPos);

                // Attempt to read a label — try known field/property names via reflection
                string label = TryGetInteractionLabel(activator) ?? root.name;

                result.Add(new NearbyInteractionEntry
                {
                    Uid  = root.name,
                    Label = label,
                    Distance = (float)Math.Round(dist, 1),
                    X = pos.x, Y = pos.y, Z = pos.z,
                });
            }
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"NearbyInteractions scan error: {ex.Message}");
        }

        result.Sort((a, b) => a.Distance.CompareTo(b.Distance));
        return result;
    }

    private static string? TryGetInteractionLabel(Il2CppSystem.Object obj)
    {
        try
        {
            var type = obj.GetIl2CppType();
            // Try common label property/field names in Outward's InteractionActivator
            foreach (var propName in new[] { "InteractionTitle", "m_interactionTitle", "Title", "Label", "m_label" })
            {
                var prop = type.GetProperty(propName,
                    Il2CppSystem.Reflection.BindingFlags.Public |
                    Il2CppSystem.Reflection.BindingFlags.NonPublic |
                    Il2CppSystem.Reflection.BindingFlags.Instance);
                if (prop != null)
                {
                    var val = prop.GetValue(obj, null);
                    if (val != null)
                    {
                        string s = val.ToString() ?? "";
                        if (!string.IsNullOrWhiteSpace(s)) return s;
                    }
                }
            }
        }
        catch { /* reflection failed — fall back to name */ }
        return null;
    }

    // ── Inventory ────────────────────────────────────────────────────────────

    private static InventoryState GetInventory()
    {
        try
        {
            var character = CharacterManager.Instance?.GetFirstLocalCharacter();
            if (character == null) return new InventoryState();

            var inv = character.Inventory;
            if (inv == null) return new InventoryState();

            var pouchItems = new List<InventoryItemEntry>();

            // Pouch (owned items container)
            var pouch = inv.Pouch;
            if (pouch != null)
            {
                var items = pouch.GetContainedItems();
                if (items != null)
                {
                    foreach (var item in items)
                    {
                        if (item == null) continue;
                        bool isFood = item.GetComponent<Food>() != null;
                        bool isEquip = item is Equipment;
                        int qty = 1;
                        if (item is ItemContainer container)
                            qty = container.ItemCount;

                        pouchItems.Add(new InventoryItemEntry
                        {
                            Name     = item.DisplayName ?? item.name,
                            ItemId   = item.ItemID,
                            Quantity = qty,
                            IsFood   = isFood,
                            IsEquipment = isEquip,
                        });
                    }
                }
            }

            // Equipped items via CharacterEquipment
            var equipped = new EquippedItems();
            var equip = inv.Equipment;
            if (equip != null)
            {
                equipped.Weapon   = equip.GetEquippedItem(EquipmentSlot.EquipmentSlotIDs.RightHand)?.DisplayName ?? "";
                equipped.OffHand  = equip.GetEquippedItem(EquipmentSlot.EquipmentSlotIDs.LeftHand)?.DisplayName ?? "";
                equipped.Armor    = equip.GetEquippedItem(EquipmentSlot.EquipmentSlotIDs.Chest)?.DisplayName ?? "";
                equipped.Helmet   = equip.GetEquippedItem(EquipmentSlot.EquipmentSlotIDs.Helmet)?.DisplayName ?? "";
                equipped.Boots    = equip.GetEquippedItem(EquipmentSlot.EquipmentSlotIDs.Foot)?.DisplayName ?? "";
            }

            return new InventoryState { Pouch = pouchItems, Equipped = equipped };
        }
        catch (Exception ex)
        {
            Plugin.Log.LogWarning($"Inventory read error: {ex.Message}");
            return new InventoryState();
        }
    }

    // ── Screen message ───────────────────────────────────────────────────────

    private static string GetScreenMessage()
    {
        // TODO: DisplayMessageManager is not present in the IL2CPP interop assemblies.
        // Screen message capture is skipped until the correct class name is confirmed
        // in Assembly-CSharp. Candidates: DisplayMessageManager, NotificationPanel,
        // ItemDisplayedManager. Add the correct type to the interop and re-enable here.
        return "";
    }

}

public class GameState
{
    [JsonPropertyName("type")] public string Type { get; init; } = "game_state";
    [JsonPropertyName("scene")] public string SceneName { get; init; } = "";
    [JsonPropertyName("player")] public PlayerState Player { get; init; } = new();
    [JsonPropertyName("nearby_dead")] public List<NearbyDeadEntry> NearbyDead { get; init; } = new();
    [JsonPropertyName("nearby_interactions")] public List<NearbyInteractionEntry> NearbyInteractions { get; init; } = new();
    [JsonPropertyName("inventory")] public InventoryState Inventory { get; init; } = new();
    [JsonPropertyName("screen_message")] public string ScreenMessage { get; init; } = "";
    [JsonPropertyName("timestamp")] public long Timestamp { get; init; }
}

public class NearbyDeadEntry
{
    [JsonPropertyName("uid")]      public string Uid    { get; init; } = "";
    [JsonPropertyName("name")]     public string Name   { get; init; } = "";
    /// <summary>"character" = died at runtime, "prop" = pre-placed/static</summary>
    [JsonPropertyName("source")]   public string Source { get; init; } = "";
    [JsonPropertyName("x")]        public float  X      { get; init; }
    [JsonPropertyName("y")]        public float  Y      { get; init; }
    [JsonPropertyName("z")]        public float  Z      { get; init; }
    [JsonPropertyName("distance")] public float  Distance { get; init; }
}

public class PlayerState
{
    [JsonPropertyName("health")] public float Health { get; init; }
    [JsonPropertyName("max_health")] public float MaxHealth { get; init; }
    [JsonPropertyName("stamina")] public float Stamina { get; init; }
    [JsonPropertyName("max_stamina")] public float MaxStamina { get; init; }
    [JsonPropertyName("mana")] public float Mana { get; init; }
    [JsonPropertyName("max_mana")] public float MaxMana { get; init; }
    [JsonPropertyName("pos_x")] public float PositionX { get; init; }
    [JsonPropertyName("pos_y")] public float PositionY { get; init; }
    [JsonPropertyName("pos_z")] public float PositionZ { get; init; }
    [JsonPropertyName("rotation_y")] public float RotationY { get; init; }
    [JsonPropertyName("camera_rotation_y")] public float CameraRotationY { get; init; }
    [JsonPropertyName("is_dead")] public bool IsDead { get; init; }
    [JsonPropertyName("in_combat")] public bool IsInCombat { get; init; }
}

public class NearbyInteractionEntry
{
    [JsonPropertyName("uid")]      public string Uid      { get; init; } = "";
    [JsonPropertyName("label")]    public string Label    { get; init; } = "";
    [JsonPropertyName("distance")] public float  Distance { get; init; }
    [JsonPropertyName("x")]        public float  X        { get; init; }
    [JsonPropertyName("y")]        public float  Y        { get; init; }
    [JsonPropertyName("z")]        public float  Z        { get; init; }
}

public class InventoryState
{
    [JsonPropertyName("pouch")]    public List<InventoryItemEntry> Pouch    { get; init; } = new();
    [JsonPropertyName("equipped")] public EquippedItems            Equipped { get; init; } = new();
}

public class InventoryItemEntry
{
    [JsonPropertyName("name")]         public string Name        { get; init; } = "";
    [JsonPropertyName("item_id")]      public int    ItemId      { get; init; }
    [JsonPropertyName("quantity")]     public int    Quantity    { get; init; } = 1;
    [JsonPropertyName("is_food")]      public bool   IsFood      { get; init; }
    [JsonPropertyName("is_equipment")] public bool   IsEquipment { get; init; }
}

public class EquippedItems
{
    [JsonPropertyName("weapon")]   public string Weapon  { get; set; } = "";
    [JsonPropertyName("off_hand")] public string OffHand { get; set; } = "";
    [JsonPropertyName("armor")]    public string Armor   { get; set; } = "";
    [JsonPropertyName("helmet")]   public string Helmet  { get; set; } = "";
    [JsonPropertyName("boots")]    public string Boots   { get; set; } = "";
}
